export const ACTIVE_DRAWER_TOGGLER = 'ACTIVE_DRAWER_TOGGLER';
export const INACTIVE_DRAWER_TOGGLER = 'INACTIVE_DRAWER_TOGGLER';
export const GET_MOCK_DATA = 'GET_MOCK_DATA';
export const SET_CONTAINER_WIDTH = 'SET_CONTAINER_WIDTH';
export const SET_CARDS_UI = 'SET_CARDS_UI';
